
    create table currency (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table order_item (
        order_item_price float(53) not null,
        order_item_quantity integer not null,
        currency_id bigint,
        id bigint generated by default as identity,
        order_id bigint,
        product_id bigint,
        primary key (id)
    );

    create table order_status (
        id integer generated by default as identity,
        status varchar(255),
        primary key (id)
    );

    create table orders (
        id bigint generated by default as identity,
        order_item_id bigint,
        order_status_id bigint,
        user_id bigint,
        date varchar(255),
        primary key (id)
    );

    create table picture (
        id bigint generated by default as identity,
        url varchar(255),
        primary key (id)
    );

    create table product_type (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table products (
        price float(53) not null,
        quantity integer not null,
        currency_id bigint,
        id bigint generated by default as identity,
        picture_id bigint,
        product_type_id bigint,
        name varchar(255),
        primary key (id)
    );

    create table users (
        admin boolean not null,
        mobile integer not null,
        id bigint generated by default as identity,
        address varchar(255),
        city varchar(255),
        country varchar(255),
        email varchar(255),
        password varchar(255),
        username varchar(255),
        primary key (id)
    );

    alter table if exists order_item 
       add constraint FKp6v8or6x76xhtn4uo1w36rr6g 
       foreign key (currency_id) 
       references currency;

    alter table if exists order_item 
       add constraint FKt4dc2r9nbvbujrljv3e23iibt 
       foreign key (order_id) 
       references orders;

    alter table if exists order_item 
       add constraint FKc5uhmwioq5kscilyuchp4w49o 
       foreign key (product_id) 
       references products;

    alter table if exists orders 
       add constraint FKp2xwgnehguaardcwjnuvukqq9 
       foreign key (order_item_id) 
       references order_item;

    alter table if exists orders 
       add constraint FK2n7p8t83wo7x0lep1q06a6cvy 
       foreign key (order_status_id) 
       references order_status;

    alter table if exists orders 
       add constraint FK32ql8ubntj5uh44ph9659tiih 
       foreign key (user_id) 
       references users;

    alter table if exists products 
       add constraint FK5x3an021g49vrd2e4glrqrj8s 
       foreign key (currency_id) 
       references currency;

    alter table if exists products 
       add constraint FKprnpl60g9fbslm1svsejqvrix 
       foreign key (picture_id) 
       references picture;

    alter table if exists products 
       add constraint FK923dhs733rpoelp2tls2ful1 
       foreign key (product_type_id) 
       references product_type;
