
    create table currency (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table order_item (
        order_item_price float(53) not null,
        order_item_quantity integer not null,
        currency_id bigint,
        id bigint generated by default as identity,
        order_id bigint,
        order_items_id bigint,
        product_id bigint,
        primary key (id)
    );

    create table order_status (
        id integer generated by default as identity,
        order_status_id bigint,
        status varchar(255),
        primary key (id)
    );

    create table orders (
        id bigint generated by default as identity,
        order_item_id bigint,
        order_status_id bigint,
        user_id bigint,
        date varchar(255),
        primary key (id)
    );

    create table picture (
        id bigint generated by default as identity,
        picture_id bigint,
        url varchar(255),
        primary key (id)
    );

    create table product_type (
        id bigint generated by default as identity,
        product_type_id bigint,
        name varchar(255),
        primary key (id)
    );

    create table products (
        price float(53) not null,
        quantity integer not null,
        currency_id bigint,
        id bigint generated by default as identity,
        picture_id bigint,
        product_id bigint,
        product_type_id bigint,
        name varchar(255),
        primary key (id)
    );

    create table users (
        admin boolean not null,
        mobile integer not null,
        id bigint generated by default as identity,
        address varchar(255),
        city varchar(255),
        country varchar(255),
        email varchar(255),
        password varchar(255),
        username varchar(255),
        primary key (id)
    );

    alter table if exists order_item 
       add constraint FKp6v8or6x76xhtn4uo1w36rr6g 
       foreign key (currency_id) 
       references currency;

    alter table if exists order_item 
       add constraint FK2l1mbvl87mtsbli1ik0ubqlru 
       foreign key (order_items_id) 
       references orders;

    alter table if exists order_status 
       add constraint FK2ka7k6otajr4rq2b9l5ib1spm 
       foreign key (order_status_id) 
       references orders;

    alter table if exists orders 
       add constraint FK32ql8ubntj5uh44ph9659tiih 
       foreign key (user_id) 
       references users;

    alter table if exists picture 
       add constraint FKqkywy7magyfg73871m108lqa5 
       foreign key (picture_id) 
       references products;

    alter table if exists product_type 
       add constraint FK4eu289ka2k6aikgmyd75wppn4 
       foreign key (product_type_id) 
       references products;

    alter table if exists products 
       add constraint FK5x3an021g49vrd2e4glrqrj8s 
       foreign key (currency_id) 
       references currency;

    alter table if exists products 
       add constraint FKguwc1xc644r7oxbljsvo4kk95 
       foreign key (product_id) 
       references order_item;
